theme: jekyll-theme-chirpy
title: Mi Blog de Ciberseguridad
description: Un blog para compartir writeups, tutoriales y proyectos de ciberseguridad.
url: "https://adperem.github.io"
github:
  username: adperem
author: Adrián
avatar: /assets/img/avatar.jpg  # Sube una imagen a esta ruta
timezone: Spain/Madrid  # Ajusta a tu zona horaria
lang: es_ES  # Para español
theme_mode: dark  # O 'light' para modo claro
paginate: 10